//The confidential and proprietary information contained in this file may only be used by a person authorised under and to the extent permitted by a subsisting licensing agreement from ARM Limited or its affiliates.
//
//  (C) Copyright 2001-2017 ARM Limited or its affiliates. All rights reserved.
//
//The entire notice above must be reproduced on all copies of this file and copies of this file may only be made by a person if such person is permitted to do so under the terms of a subsisting license agreementfrom ARM Limited or its affiliates.
`define RNG_EXISTS
`define RNG_BIST_EXISTS
`define TRNG_TESTS_BYPASS_EN  
`define CRNGT_EXISTS     
`define AUTOCORR_EXISTS    
`define EHR_WIDTH 192
`define AUTOCORR_192_BITS
